name: cloud-torrent
image: ubuntu-16-04-x64
config:
  #cloud-config
  packages:
    - git
    - docker
  runcmd:
    - docker run -d -p 3000:3000 -v /path/to/my/downloads:/downloads jpillora/cloud-torrent